config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/welcome", to: "pages#welcome"
  get "/finish_game", to: "pages#finish_game"
  get "/admin", to: "pages#admin"
  resources :competences, only: [ :index, :show ]
  resources :questions, only: [ :show ]
  resources :user_answers, only: [ :create, :update]
  resources :games, only: [ :new, :create, :show ] do
    resources :questions, only: [ :new, :create ]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_feedback_answer.html.erb
<div class="container">
  <div class="top-pading-question-show list-display-feedback"> <!-- Why is the bottom button included in this? -->
    <!-- List of all the answers -->
    <ul class="list-group list-group-flush">
      <%= hidden_field_tag(:question_id, @question.id) %>
      <% @question.answers.each do |answer| %>
        <% if answer.correct == true %>
          <li class="list-group-item bg-info d-flex">
            <p class="feedback-base-text base-text"><i class="fas fa-thumbs-up text-danger">&nbsp;</i></p>
            <p class="feedback-base-text base-text">&nbsp;-&nbsp;<%= answer.content %></p>
          </li>
        <!--  in case we want to show all answers again:
        <% #else %>
          <li class="list-group-item d-flex">
            <p class="base-text"><i class="far fa-thumbs-down"></i>&nbsp;</p>
            <p class="base-text">&nbsp;-&nbsp;<%= answer.content %></p>
          </li> -->
        <% end %>
      <% end %>
    </ul>
    <p class="base-text"><%= @question.feedback.html_safe %></p>

  </div> <!-- list-display-feedback end -->

    <!-- link after the feedback -->
  <div class="fixed-bottom bg-white">
    <% if @question == @game.questions.last %>
      <%= link_to "Finish Game!", finish_game_path, class: "btn btn-lg btn-primary btn-answer-block" %>
    <% else %>
      <%= link_to "Next question!", question_path(@next_question.id), class: "btn btn-lg btn-primary btn-answer-block" %>
    <% end %> <!-- Link end -->
  </div>
</div> <!-- Container end -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon d-flex">
  <!-- Logo -->
  <%= link_to competences_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_150.png", height: 50 %>
  <% end %>
  <h3>UpSkill</h3>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right d-flex">

    <% if user_signed_in? and current_user.role == 'admin' %>

      <!-- Hamburger with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div data-toggle="dropdown">
            <i class="fas fa-bars" id="navbar-wagon-menu"></i>
          </div>
          <%#= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "/admin" do %>
                <% if current_user.role == 'admin' %>
                  <i class="fas fa-unlock-alt"></i>
                <% else %>
                  <i class="fas fa-lock"></i>
                <% end %>
                <%= t(".admin", default: "Admin") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% elsif user_signed_in? %>
      <!-- Non-Admin log out -->
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-sign-out-alt navbar-logout-color"></i>
      <% end %>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "<i class='fas fa-sign-in-alt'></i>".html_safe), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <!-- Bootstrap dropdown -->
  <!-- <div class="btn-group">
    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Right-aligned menu
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <button class="dropdown-item" type="button">Action</button>
      <button class="dropdown-item" type="button">Another action</button>
      <button class="dropdown-item" type="button">Something else here</button>
    </div>
  </div> -->

  <!-- Le Wagon menu not working with Bootstrap 4 -->
  <!-- <div class="navbar-wagon-item d-md-none">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->

</div>

app/views/shared/_question_display.html.erb
<div class="container">
  <div class="top-pading-question-show list-display-question">
    <p class="base-text"><%= @question.content.html_safe %></p>

    <%= simple_form_for @user_answer do |f| %>
      <ul class="list-group list-group-flush">
        <%= f.input :question_id, :as => :hidden %>
        <%= f.input :chosen_answer_id, as: :radio_buttons, collection: answer_collection_for_question(@question), label: false, item_wrapper_tag: :li, item_wrapper_class: "list-group-item d-flex base-text" %>
      </ul>

       <div class="fixed-bottom bg-white">
        <%= f.button :submit, "Check my answer!", class: "btn btn-lg btn-danger btn-answer-block" %>
       </div>
    <% end %>
  </div>

</div> <!-- Container end -->

app/views/shared/_question_openfield.html.erb
<div class="top-pading-question-show list-display-question">
  <p><%= @question.content %></p>

  <div class="question_field">
    <%= form_for(user_answers_path, :method => "post") do |f| %>
      <%= f.text_area :question_id, :placeholder => "Type your thoughts in here" %>
      <%= hidden_field_tag(:question_id, @question.id) %>
    <% end %>
  </div>

  <!-- submit -->
  <div>
    <%= submit_tag("Check my answer!", class: "btn btn-lg btn-danger fixed-bottom btn-answer-block") %>
  </div>

</div>

app/views/shared/_question_photo.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="picture-padding">
        <%= image_tag("#{@question.photo}", alt: "#{@question.photo}", width: 250) %>
      </div>
    </div>

    <div class="col-12 col-md-6 offset-md-3 top-pading-question-show">
      <p class="base-text"><%= @question.content.html_safe%></p>
      <%= simple_form_for @user_answer do |f| %>
        <ul class="list-group list-group-flush">
          <%= f.input :question_id, :as => :hidden %>
          <%= f.input :chosen_answer_id, as: :radio_buttons, collection: answer_collection_for_question(@question), label: false, item_wrapper_tag: :li, item_wrapper_class: "list-group-item d-flex base-text" %>
        </ul>

        <div class="fixed-bottom bg-white">
          <%= f.button :submit, "Check my answer!", class: "btn btn-lg btn-danger btn-answer-block" %>
        </div>
      <% end %>
    </div>

  </div> <!-- end of row -->
</div> <!-- end of container -->

app/views/shared/_question_video.html.erb
<div class="container">
  <div class="row">

    <div class="col-12 col-md-6 offset-md-3 video-padding">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe
          class="embed-responsive-item"
          src="https://www.youtube.com/embed/<%= @question.video %>?rel=0&amp;start=7"
          frameborder="0"
          allowfullscreen>
        </iframe>
      </div>
    </div>

    <div class="col-12 col-md-6 offset-md-3 top-pading-question-show">
      <p class="base-text"><%= @question.content.html_safe%></p>
      <%= simple_form_for @user_answer do |f| %>
        <ul class="list-group list-group-flush">
          <%= f.input :question_id, :as => :hidden %>
          <%= f.input :chosen_answer_id, as: :radio_buttons, collection: answer_collection_for_question(@question), label: false, item_wrapper_tag: :li, item_wrapper_class: "list-group-item d-flex base-text" %>
        </ul>

        <div class="fixed-bottom bg-white">
          <%= f.button :submit, "Check my answer!", class: "btn btn-lg btn-danger btn-answer-block" %>
        </div>
      <% end %>
    </div>

  </div> <!-- end of row -->
</div> <!-- end of container -->