config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/welcome", to: "pages#welcome"
  get "/finish_game", to: "pages#finish_game"
  get "/admin", to: "pages#admin"
  resources :competences, only: [ :index, :show ]
  resources :questions, only: [ :show ]
  resources :user_answers, only: [ :create, :update]
  resources :games, only: [ :new, :create, :show ] do
    resources :questions, only: [ :new, :create ]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/admin.html.erb
<% if current_user.role != "admin" %>
  <div class="container"> <!-- for non-admins -->
    <div class="row">
      <div class="col-12">
        <h3 class="text-center deny-header"><i class="fas fa-ban text-danger"></i> You do not have access to this content <i class="fas fa-lock text-danger"></i></h3>
      </div>
    </div>
  <div> <!-- Container end -->
<% else %>
  <!-- For admins -->
  <div class="container-fluid" id="ProgressBarAdmin">
    <div class="row">
      <!-- Links to new and edit -->
      <div class="col-12 text-center">
        <%= link_to "Create a new game", new_game_path, class: "btn btn-lg btn-danger deny-header" %>
      </div>
    </div> <!-- row end -->

    <div class="row"> <!-- Statistics -->
      <!-- progress bar showing average of all user answers compared to total answers -->
      <div class="col-12">
        <h3 class="deny-header">Average User Progress: <strong><span id="adminText"></span></strong></h3>
        <div class="progress mt-auto">
          <div id="goalBarAdmin"
          class="progress-bar bg-primary"
          role="progressbar"
          aria-valuenow="<%= @user_answers * 100 / @users.size / @question_all %>" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
          </div>
        </div>
      </div>
    </div> <!-- Row end -->

    <div class="row">
      <div class="col-12 header-margin-count">
      </div>
      <div class="col-12 col-md-4">
        <h3>Competences <span class="badge badge-pill badge-danger"><%= @competences_all.size %></span></h3>
      </div>
      <div class="col-12 col-md-4">
        <h3>Games <span class="badge badge-pill badge-danger"><%= @games_all.size %></span></h3>
      </div>
      <div class="col-12 col-md-4">
        <h3>Questions <span class="badge badge-pill badge-danger"><%= @question_all %></span></h3>
      </div>
      <div class="col-12 footer-margin-count">
      </div>
    <% @competences_all.each do |competence| %> <!-- Show all competences -->
      <div class="col-12 col-md-6 col-lg-3 text-center">
        <div class="card text-white competence-body-link
          <%= competence.color.name %>"> <!-- Card with background color set according to class -->
          <div class="card-body d-flex flex-column">
            <h4><%= competence.name %></h4>
            <div class="text-under-card-icon">
              <i class="<%= competence.color.icon %> fa-9x img-fluid"></i>
            </div>
            <h5 class="mt-auto p-2">Games: <%= @games_all.where(competence_id: competence).size %></h5>
            <h5>Questions: <%= @question_all_list.where(game_id: (@games_all.where(competence_id: competence))).size %></h5>
          </div>
          <%= link_to "", competence_path(competence), class: "competence-link" %>
        </div> <!-- Card end -->
      </div> <!-- Col end -->
    <% end %> <!-- Loop end -->
    <% @users.each do |user| %> <!-- Users -->
      <div class="col-12 header-margin-count">
        <h4><%= user.name %></h4>
        <p>Answers: <%= user.user_answers.size %></p>
      </div>
    <% end %> <!-- Users end -->

    </div> <!-- Row end -->

  </div> <!-- Container-fluid end -->
<% end %>

app/views/pages/finish_game.html.erb
<div class="finish container-fluid container-0padding">
  <div class="mx-auto div-logo" id="JS-on-finish-page">
  <div class="d-flex text-center justify-content-center logo-placement"><%= image_tag "logo-crown.png", alt: "logo", height: 300 %>
  </div>
</div>

<div class="div-text">
  <div class="goodbye-text-padding">
    <h2>Congratulations<br><%= current_user.name %>!</h2>
    <p>You achieved <strong><%= @questions_correct %> <i class='far fa-check-circle text-primary'></i> of <%= @question_count %></strong> in this game!</p>
    <br><p>Wanna keep on playing?<br><i class="fas fa-arrow-circle-down"></i><b> Choose your next skill! <b><i class="fas fa-arrow-circle-down"></i></p>
  </div>
</div>

<div class="fixed-bottom div-bottom-competences"> <!-- fix the competences to the bottom -->
  <div class="d-flex text-center justify-content-center"> <!-- give size to the competences line -->
    <% @competences.each do |competence| %>
      <div class="card card-no-br text-white <%= competence.color.name %> mb-3 competence-body-link d-flex flex-column"> <!-- Card -->
        <div class="card-body d-flex flex-column">
          <div class="mt-auto">
            <i class="<%= competence.color.icon %> fa-9x img-fluid image-size-control"></i>
          </div>
        </div>
        <%= link_to "", competence_path(competence), class: "competence-link" %>
      </div> <!-- Col end -->
    <% end %> <!-- Loop end -->
  </div> <!-- flex -->
</div> <!-- fixed bottom -->
</div>

app/views/pages/home.html.erb
<!-- Uggly hack to remove the default navbar on this page only! -->
<% content_for :navbar do %>
<input type="hidden">
<% end %>

<div class="container-fluid container-0padding">
  <!-- Flexbox used to place logo and other elements over the design bars -->
  <div class="position-absolute logo-placement d-flex flex-column justify-content-center"> <!-- container for logo and header -->
    <div class="d-flex justify-content-center">
      <%= image_tag("logo_150.png", class: "d-block d-md-none") %>
      <%= image_tag("logo_300.png", class: "d-none d-md-block") %>
    </div>
    <div class="d-flex justify-content-center">
      <h1 class="margin-title size-title text-white text-center d-block d-md-none">Work. Play. Learn.</h1>
      <h1 class="margin-title text-white text-center d-none d-md-block">Work. Play. Learn</h1>
    </div>
    <div class="d-flex justify-content-center margin-button">
      <!-- Login modal button -->
      <% if current_user %>
        <h5 class="text-white d-block d-md-none size-title">Start to Play!</h5>
        <h5 class="text-white d-none d-md-block">Start to Play!</h5>
      <% else %>
        <button class="btn btn-lg button-opacity text-white d-block d-md-none size-title" data-toggle="modal" data-target="#loginModal">Login</button>
        <button class="btn btn-lg button-opacity large-text text-white d-none d-md-block" data-toggle="modal" data-target="#loginModal">Login</button>
      <% end %>
    </div>
  </div> <!-- logo and header end -->
  <div class="row col-color-bar bg-my-black"></div>
  <div class="row col-color-bar bg-dark"></div>
  <div class="row col-color-bar bg-success"></div>
  <div class="row col-color-bar bg-info"></div>
  <div class="row col-color-bar bg-my-md-info"></div>
  <div class="row col-color-bar bg-primary"></div>
  <div class="row col-color-bar bg-my-bright-primary"></div>
  <div class="row col-color-bar bg-warning"></div>
  <div class="row col-color-bar bg-my-bright-warning"></div>
  <div class="row col-color-bar bg-danger"></div>
  <div class="row col-color-bar-last bg-my-bright-danger"></div>
  <!-- <div class="row col-color-bar bg-light"></div> -->
  <% if current_user %>
    <a class="competence-link" href="/competences" ></a>
  <% end %>
</div>

<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel">Login to start</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <!-- Rails devise -->
        <%= simple_form_for(resource, :as => resource_name, url: session_path(resource_name)) do |f| %>
          <div class="form-inputs">
            <%= f.input :email, required: false, autofocus: true %>
            <%= f.input :password, required: false %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Log in", class: "btn btn-lg btn-primary btn-block text-white" %>
          </div>
          <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-sm btn-warning text-white margin-button" %>
        <% end %>
        <!-- Rails devise end -->
      </div>
    </div>
  </div>
</div> <!-- Modal end -->

app/views/pages/welcome.html.erb
<h1>Pages#welcome</h1>
<p>Find me in app/views/pages/welcome.html.erb</p>